### ISSUE TITLE
koffer config failure to honor alternate organization in plugin stanza

### ISSUE THREAD

**Issue by usrbinkat** [ContainerCraft/koffer-go#2]
### Expected result:
Koffer should honor the config and it's declared running variables as printed to screen

### Actual result:
Koffer prints correct `User/Path:` variable to screen but persists in pulling against default codesparta plugin repo
```
[core@unicorn ~]$ sudo podman run -itq --rm --pull always --volume ${HOME}/bundle:/root/bundle:z --volume ${HOME}/.docker:/root/.docker:z --volume /tmp/sparta.yml:/root/.koffer/config.yml:z  docker.io/containercraft/koffer:4.5.14 bundle --silent
Running Koffer Bundle....
 >>  Running Plugin:  cloudctl

    Service: github.com
  User/Path: containercraft
     Plugin: cloudctl
        Ref: master
       Dest: /root/koffer
        URL: https://github.com/codesparta/cloudctl
        CMD: git clone https://github.com/codesparta/cloudctl /root/koffer

 >>  git clone https://github.com/codesparta/cloudctl /root/koffer
Could not clone https://github.com/codesparta/cloudctl for cloudctl
```

### Testing Method:
  1. place config
```
cat <<EOF >/tmp/sparta.yml
koffer:
  silent: false
  plugins:
    cloudctl:
      version: master
      service: github.com
      organization: containercraft
EOF
```
  2. Place quay pull secret:
```
vi ~/.docker/config.json
```
  3. Run Koffer
```
sudo podman run -itq --rm --pull always \
    --volume ${HOME}/.docker:/root/.docker:z \
    --volume /tmp/sparta.yml:/root/.koffer/config.yml:z  \
  docker.io/containercraft/koffer:4.5.14 bundle --silent
```

### Workaround:
Manually declare plugin & source project on cli with flags:
```
sudo podman run -itq --rm --pull always \
    --volume ${HOME}/bundle:/root/bundle:z \
    --volume ${HOME}/.docker:/root/.docker:z \
  docker.io/containercraft/koffer:4.5.14 bundle --silent \
    --plugin cloudctl --user containercraft
...
Running Koffer Bundle....
 >>  Running Plugin:  cloudctl

    Service: github.com
  User/Path: containercraft
     Plugin: cloudctl
        Ref: master
       Dest: /root/koffer
        URL: https://github.com/containercraft/cloudctl
        CMD: git clone https://github.com/containercraft/cloudctl /root/koffer

 >>  git clone https://github.com/containercraft/cloudctl /root/koffer
commit 5e1593105dabea32f76aac8005f2299337356f9c
Author: usrbinkat <usrbinkat@braincraft.io>
Date:   Sun Oct 18 15:26:46 2020 -0700
```

**Comment by usrbinkat** [comment]
Thought for discussion. Perhaps we can unify the `--user` and `organization` cli/yaml config vars with

`--project` and `    project: ${name}`

EG: (yaml)
```
koffer:
  silent: false
  plugins:
    cloudctl:
      version: master
      service: github.com
      project: containercraft
```
